### PR TITLE
Update readme to include build instructions for OSX.

### PR DESCRIPTION
**Pull request by DctrBinary**

### CODE REVIEW

**Comment by DctrBinary** [comment]
That looks a lot better to me.

**Comment by marechal-p** [comment]
@DctrBinary may I squash and rewrite your commit message ?

**Comment by marechal-p** [comment]
TBF I'm trying to find how to properly review PRs in order to do it more efficiently next time.

I know it was simply writing your instructions in a README, but now I got this ! :)

**Comment by marechal-p** [comment]
Thank you again @DctrBinary !

**Pull request merged**
