### PR TITLE
Adding a reference to current upbge builds...

### PR DESCRIPTION
**Pull request by trevortomesh**
... so people stop complaining.

### CODE REVIEW

**Comment by trevortomesh** [comment]
... if it pleases the council.

**Comment by marechal-p** [comment]
Please rebase to remove the noise from your history, and squash what is left. Then push force on your PR branch so that it is updated.

**Comment by trevortomesh** [comment]
This might be irrelevant now as we have a ketsji build.

**Comment by marechal-p** [comment]
Maybe, if you think so then maybe add a reference to it.

**Pull request closed without merging**
